name: atlantic_web3_passkey
description: A BIP39 (https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) compatible library for Flutter writing by Dart.
version: 0.0.1
homepage: http://atlantic.lat

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  #atlantic web3
  atlantic_web3:
    path: ../atlantic_web3
  #providers
  web3_providers_http:
    path: ../web3_providers_http
  web3_providers_ipc:
    path: ../web3_providers_ipc
  web3_providers_ws:
    path: ../web3_providers_ws

  http: ^0.13.5
  crypto: ^3.0.2
  convert: ^3.1.1
  hex: ^0.2.0
  bip32: ^2.0.0
  bip39: ^1.0.6
  dart_bip32_bip44: ^0.2.0

  pointycastle: ^3.0.1
  bs58check: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
