name: atlantic_web3_passkey
description: A BIP39 (https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) compatible library for Flutter writing by Dart.
version: 0.0.1
homepage: http://atlantic.lat

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  #atlantic web3
  atlantic_web3:
    path: ../atlantic_web3

  #providers
  web3_providers_http:
    path: ../web3_providers_http
  web3_providers_ipc:
    path: ../web3_providers_ipc
  web3_providers_ws:
    path: ../web3_providers_ws

  #para guardar el passkey
  path: ^1.8.1
  path_provider: ^2.0.8
  device_info_plus: ^8.2.0
  sqlite3: ^2.3.0
  sqlite3_flutter_libs: ^0.5.19+1

  encrypt: ^5.0.3
  pointycastle: ^3.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
