name: atlantic_web3
description: Biblioteca Dart para trabajar con la web3
version: 0.0.1

publish_to: https://dart.pkg.jetbrains.space/novasoftware/p/atlantic-web-3/atlantic-web3/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  #modulos de atlantic web3
  atlantic_web3_passkey:
    path: ../atlantic_web3_passkey
  atlantic_web3_authentication:
    path: ../atlantic_web3_authentication
  atlantic_web3_payment:
    path: ../atlantic_web3_payment
  atlantic_web3_contract:
    path: ../atlantic_web3_contract
  atlantic_web3_gasfee:
    path: ../atlantic_web3_gasfee
  atlantic_web3_storage:
    path: ../atlantic_web3_storage
  atlantic_web3_blockchain:
    path: ../atlantic_web3_blockchain

  #providers
  web3_providers_http:
    path: ../web3_providers_http
  web3_providers_ipc:
    path: ../web3_providers_ipc
  web3_providers_ws:
    path: ../web3_providers_ws

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
