name: atlantic_web3
description: Biblioteca Dart para conectarse a clientes de Ethereum. ¡Envíe transacciones e interactúe con contratos inteligentes!
version: 0.0.1

publish_to: https://dart.pkg.jetbrains.space/novasoftware/p/atlantic-web-3/atlantic-web3/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  #atlantic web3
  atlantic_web3_eth:
    path: ../atlantic_web3_eth
  atlantic_web3_net:
    path: ../atlantic_web3_net
  atlantic_web3_utils:
    path: ../atlantic_web3_utils
  #providers
  atlantic_web3_providers_http:
    path: ../atlantic_web3_providers_http
  atlantic_web3_providers_ipc:
    path: ../atlantic_web3_providers_ipc
  atlantic_web3_providers_ws:
    path: ../atlantic_web3_providers_ws

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
