name: atlantic_web3
repository: https://github.com/atlantic-finance/atlantic_web3

ide:
  intellij:
    enabled: true

packages:
  - packages/*

scripts:
  ping: echo 'Hello World'

  get:
    run: |
      melos exec -- "flutter pub get"
    description: Get dependencies.
    packageFilters:
      flutter: true

  format:
    run: |
      melos exec -- "flutter format --output=none --set-exit-if-changed ."
    description: Verify formatting.
    packageFilters:
      flutter: true

  analyze:
    run: |
      melos exec -- "flutter analyze --fatal-infos"
    description: Analyze project source.
    packageFilters:
      flutter: true

  test:
    run: |
      melos exec -- "flutter test"
    description: Run `flutter test` for a specific package.
    packageFilters:
      flutter: true
