name: atlatic_web3
repository: https://github.com/atlantic-finance/atlantic_web3

ide:
  intellij:
    enabled: true

packages:
  - packages/*

scripts:
  hello: echo 'Hello World'

  format:
    run: |
      melos exec -- "flutter format --output=none --set-exit-if-changed ."
    description: Verify formatting.

  analyze:
    run: |
      melos exec -- "flutter analyze --fatal-infos"
    description: Analyze project source.

  test:
    run: |
      melos exec -- "flutter test"
    description: Run `flutter test` for a specific package.   

  build:android:
    run: |
      melos exec -- "flutter build apk"
    description: Build a specific example app for Android.

  build:ios:
    run: |
      melos exec -- "flutter build ios --no-codesign"
    description: Build a specific example app for iOS.
  

