name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  get_dependencies:
    name: "Get dependencies"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: "Print Dart SDK Version"
        run: dart --version
      - uses: actions/cache@v2
        with:
          path: .dart_tool
          key: dart-dependencies-${{ hashFiles('pubspec.yaml') }}
      - name: "Get dependencies"
        env:
          PUB_CACHE: ".dart_tool/pub_cache"
        run: dart pub upgrade

  analyze:
    name: "Analysis"
    needs: get_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: .dart_tool
          key: dart-dependencies-${{ hashFiles('pubspec.yaml') }}
      - uses: dart-lang/setup-dart@v1
      - run: "dart format --output=none --set-exit-if-changed ."
      - run: dart analyze --fatal-infos

  browser_tests:
    name: "Unit Tests (Browser)"
    needs: get_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: .dart_tool
          key: dart-dependencies-${{ hashFiles('pubspec.yaml') }}
      - uses: dart-lang/setup-dart@v1
      - run: dart test -x expensive --platform chrome,firefox

