name: atlantic_web3_core
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

  pointycastle: ^3.6.2
  sec: ^1.0.1
  http: ^0.13.5
  uuid: ^3.0.7
  json_rpc_2: ^3.0.2
  stream_transform: ^2.1.0
  stream_channel: ^2.1.1
  eip55: ^1.0.2
  eip1559: ^0.6.1
  typed_data: ^1.3.1
  convert: ^3.1.1
  async: ^2.10.0
  wallet: ^0.0.10
  web_socket_channel: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
