name: atlantic_web3_eth
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  pointycastle: ^3.6.2
  sec: ^1.0.1
  http: ^0.13.5
  uuid: ^3.0.7
  json_rpc_2: ^3.0.2
  stream_transform: ^2.1.0
  stream_channel: ^2.1.1
  eip55: ^1.0.2
  eip1559: ^0.6.1
  typed_data: ^1.3.1
  convert: ^3.1.1
  async: ^2.10.0
  wallet: ^0.0.10
  web_socket_channel: ^2.2.0

  #atlantic web3
  atlantic_web3_core:
    path: ../atlantic_web3_core
  atlantic_web3_eth_abi:
    path: ../atlantic_web3_eth_abi
  atlantic_web3_eth_accounts:
    path: ../atlantic_web3_eth_accounts
  atlantic_web3_eth_contract:
    path: ../atlantic_web3_eth_contract
  atlantic_web3_eth_ens:
    path: ../atlantic_web3_eth_ens
  atlantic_web3_eth_iban:
    path: ../atlantic_web3_eth_iban
  atlantic_web3_eth_personal:
    path: ../atlantic_web3_eth_personal

  #providers
  atlantic_web3_providers_http:
    path: ../atlantic_web3_providers_http
  atlantic_web3_providers_ipc:
    path: ../atlantic_web3_providers_ipc
  atlantic_web3_providers_ws:
    path: ../atlantic_web3_providers_ws

dev_dependencies:
  test: ^1.17.1
