include: package:lints/recommended.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
  language:
    strict-raw-types: false
  strong-mode:
    implicit-casts: true
    implicit-dynamic: false
  errors:
    always_declare_return_types: error
    always_specify_types: error
    annotate_overrides: error
    argument_type_not_assignable: error
    avoid_function_literals_in_foreach_calls: error
    avoid_renaming_method_parameters: error
    avoid_types_on_closure_parameters: error
    avoid_unnecessary_containers: error
    await_only_futures: error
    body_might_complete_normally_nullable: error
    camel_case_types: error
    curly_braces_in_flow_control_structures: error
    dead_code: error
    duplicate_import: error
    file_names: error
    implicit_dynamic_function: ignore
    implicit_dynamic_parameter: error
    implicit_dynamic_list_literal: ignore
    implicit_dynamic_map_literal: ignore
    implicit_dynamic_method: ignore
    implicit_dynamic_type: ignore
    implicit_dynamic_variable: ignore
    invalid_assignment: error
    missing_return: error
    must_be_immutable: error
    prefer_adjacent_string_concatenation: error
    prefer_const_constructors: error
    prefer_const_constructors_in_immutables: error
    prefer_const_declarations: error
    prefer_collection_literals: error
    prefer_contains: error
    prefer_const_literals_to_create_immutables: error
    prefer_interpolation_to_compose_strings: error
    prefer_is_empty: error
    prefer_final_fields: error
    prefer_single_quotes: error
    public_member_api_docs: error
    require_trailing_commas: error
    sized_box_for_whitespace: error
    sort_constructors_first: error
    sort_unnamed_constructors_first: error
    todo: ignore
    use_function_type_syntax_for_parameters: error
    use_key_in_widget_constructors: error
    unnecessary_import: error
    unnecessary_type_check: error
    unnecessary_string_interpolations: error
    unnecessary_this: error
    unused_element: error
    unused_import: error
    unused_local_variable: error
    use_rethrow_when_possible: error
linter:
  rules:
    avoid_print: false
    prefer_interpolation_to_compose_strings: true
    prefer_single_quotes: true
    public_member_api_docs: flase
    require_trailing_commas: true
    #    always_use_package_imports: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
