name: atlantic_web3
description: Dart library to connect to Ethereum clients. Send transactions and interact with smart contracts!
version: 2.6.1
homepage: https://pwa.ir
repository: https://github.com/xclud/web3dart

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  #atlantic web3
  atlantic_web3_eth:
    path: ../atlantic_web3_eth
  atlantic_web3_net:
    path: ../atlantic_web3_net
  atlantic_web3_utils:
    path: ../atlantic_web3_utils
  #providers
  atlantic_web3_providers_http:
    path: ../atlantic_web3_providers_http
  atlantic_web3_providers_ipc:
    path: ../atlantic_web3_providers_ipc
  atlantic_web3_providers_ws:
    path: ../atlantic_web3_providers_ws

dev_dependencies:
  test: ^1.22.0
  lints: ^2.0.0
