name: atlantic_bip39
description: A BIP39 (https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) compatible library for Flutter writing by Dart.
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

  atlantic_web3:
    path: ../atlantic_web3

  http: ^0.13.5
  crypto: ^3.0.2
  convert: ^3.1.1
  hex: ^0.2.0
  bip32: ^2.0.0
  bip39: ^1.0.6
  dart_bip32_bip44: ^0.2.0

  pointycastle: ^3.0.1
  bs58check: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
