name: web3_providers_ipc
version: 0.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  #atlantic web3
  atlantic_web3:
    path: ../atlantic_web3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
