name: atlantic_web3_net
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

  #atlantic web3
  atlantic_web3_core:
    path: ../atlantic_web3_core
  #providers
  atlantic_web3_providers_http:
    path: ../atlantic_web3_providers_http
  atlantic_web3_providers_ipc:
    path: ../atlantic_web3_providers_ipc
  atlantic_web3_providers_ws:
    path: ../atlantic_web3_providers_ws

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
