name: atlantic_web3_providers_http
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  #client
  http: ^0.13.5
  #atlantic web3
  atlantic_web3_core:
    path: ../atlantic_web3_core

dev_dependencies:
  test: ^1.17.1
