name: atlantic_web3_eth_iban
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  #atlantic web3
  atlantic_web3_core:
    path: ../atlantic_web3_core

dev_dependencies:
  test: ^1.17.1
