# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Continuous Delivery

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Clone source code
        uses: actions/checkout@v2

      - name: Get java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Get flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.8'
          channel: 'stable'

      - name: Show flutter version
        run: flutter --version

      - name: Install melos CLI
        run: flutter pub global activate melos

      - name: Install dependencies
        run: melos run get --no-select
